#!/bin/bash

######################################################################
# Copyright (c). All rights reserved                                 #
# GNU GENERAL PUBLIC LICENSE                                         #
# Version 3, 29 June 2007                                            #
#                                                                    #
# Coded by Solomon Narh (::XploitsR Author::)                        #
# Github: https://github.com/XploitsR/XRMailer                       #
# Facebook: https://facebook.com/RXploits                            #
# Twitter: https://twitter.com/RXploits                              #
# Telegram: https://t.me/RXploits                                    #
# Website: https://xploitsr.tk                                       #
#                                                                    #
#             ::PERSONAL ME::                                        #
# Github: https://github.com/XploitsR/XRMailer                       #
# Facebook: https://facebook.com/solomon.narh.311                    #
# Twitter: https://twitter.com/solomon97062                          #
# Instagram: @_xploitsr_author_1                                     #
# Email: solomonnarh97062@gmail.com                                  #
######################################################################

clear
path=`pwd`
xrlog="$path/.xrlog/xrlog"

if [ -f "$xrlog" ] || [ ! -f "$xrlog" ]
then

cyan='\e[0;36m'
green='\e[0;32m'
red='\e[1;31m'
yellow='\e[1;33m'
whiteBlink='\e[1;5m'
path=`pwd`
file="$path/xrmailer.py"

sleep 1

Banner(){

source banner

}
Credits(){
echo "
        [== XploitsR Authors ==]
[============================================]
          == Full Programmer ==
              Solomon Narh

            == His Email ==
       solomonnarh97062@gmail.com

        == His Facebook Account ==

   https://facebook.com/solomon.narh.311

           [== Contributors ==]
[============================================]
           == HTML Developer ==
             Dharmesh Pandey

            == His Email ==
       dharmeshpandey001@gmail.com

        == His Facebook Account ==
   https://facebook.com/dharmeshspandey
[============================================]
"
}

Usage(){

echo "Usage: xrmailer [OPTION] "
echo "OPTIONS:"
echo " "
echo "       --start :: for starting up xrmailer"
echo "       --setup :: for setting up xrmailer for the first time"
echo "       --help  :: print this screen"
echo "       --version :: print xrmailer version"
echo "       --credits :: show developers && contributors"
echo " "
echo "Start:"
echo "     xrmailer --start"
echo " "

}

Version(){

echo "XRMailer::Version->1.0.3"

}

if [ "$1" = '--help' ]
then
sleep 2

   Banner
   Usage

elif [ "$1" = '--version' ]
then
sleep 2

   Banner
echo " "
   Version

elif [ "$1" = '--setup' ];then
chmod +x setup.sh && ./setup.sh

elif [ "$1" = '--credits' ];then
Credits

elif [ "$1" = '--start' ] && [ -f "$xrlog" ]
then
echo " "
sleep 3

Banner
echo " "
sleep 2
echo  "[*] ::Compose Mail:: "
sleep 2

if [ -f "$file" ] 
then

python3 $file

sleep 3

else
echo -e $red"[!] ::Mailer(file) not found:: "
sleep 2
echo -e $red"[!] ::Aborting:: "
sleep 3
fi
else
sleep 2

   Banner
echo " "
   Usage
fi
else
echo "[!] Please Run The Setup"
echo "[*] Type: xrmailer --setup"
exit 1
fi
